export default [
    {
        hits: 0,
        misses: 0,
        url: "a-hiragana",
        name: "a",
    },
    {
        hits: 0,
        misses: 0,
        url: "i-hiragana",
        name: "i",
    },
    {
        hits: 0,
        misses: 0,
        url: "mi-hiragana",
        name: "mi",
    },
    {
        hits: 0,
        misses: 0,
        url: "nu-hiragana",
        name: "nu",
    },
    {
        hits: 0,
        misses: 0,
        url: "se-hiragana",
        name: "se",
    },
    {
        hits: 0,
        misses: 0,
        url: "u-hiragana",
        name: "u",
    },
    {
        hits: 0,
        misses: 0,
        url: "chi-hiragana",
        name: "chi",
    },
    {
        hits: 0,
        misses: 0,
        url: "ka-hiragana",
        name: "ka",
    },
    {
        hits: 0,
        misses: 0,
        url: "mo-hiragana",
        name: "mo",
    },
    {
        hits: 0,
        misses: 0,
        url: "o-hiragana",
        name: "o",
    },
    {
        hits: 0,
        misses: 0,
        url: "shi-hiragana",
        name: "shi",
    },
    {
        hits: 0,
        misses: 0,
        url: "wa-hiragana",
        name: "wa",
    },
    {
        hits: 0,
        misses: 0,
        url: "e-hiragana",
        name: "e",
    },
    {
        hits: 0,
        misses: 0,
        url: "ke-hiragana",
        name: "ke",
    },
    {
        hits: 0,
        misses: 0,
        url: "mu-hiragana",
        name: "mu",
    },
    {
        hits: 0,
        misses: 0,
        url: "ra-hiragana",
        name: "ra",
    },
    {
        hits: 0,
        misses: 0,
        url: "so-hiragana",
        name: "so",
    },
    {
        hits: 0,
        misses: 0,
        url: "wo-hiragana",
        name: "wo",
    },
    {
        hits: 0,
        misses: 0,
        url: "fu-hiragana",
        name: "fu",
    },
    {
        hits: 0,
        misses: 0,
        url: "ki-hiragana",
        name: "ki",
    },
    {
        hits: 0,
        misses: 0,
        url: "na-hiragana",
        name: "na",
    },
    {
        hits: 0,
        misses: 0,
        url: "re-hiragana",
        name: "re",
    },
    {
        hits: 0,
        misses: 0,
        url: "su-hiragana",
        name: "su",
    },
    {
        hits: 0,
        misses: 0,
        url: "ya-hiragana",
        name: "ya",
    },
    {
        hits: 0,
        misses: 0,
        url: "ha-hiragana",
        name: "ha",
    },
    {
        hits: 0,
        misses: 0,
        url: "ko-hiragana",
        name: "ko",
    },
    {
        hits: 0,
        misses: 0,
        url: "ne-hiragana",
        name: "ne",
    },
    {
        hits: 0,
        misses: 0,
        url: "ri-hiragana",
        name: "ri",
    },
    {
        hits: 0,
        misses: 0,
        url: "ta-hiragana",
        name: "ta",
    },
    {
        hits: 0,
        misses: 0,
        url: "yo-hiragana",
        name: "yo",
    },
    {
        hits: 0,
        misses: 0,
        url: "he-hiragana",
        name: "he",
    },
    {
        hits: 0,
        misses: 0,
        url: "ku-hiragana",
        name: "ku",
    },
    {
        hits: 0,
        misses: 0,
        url: "n-hiragana",
        name: "n",
    },
    {
        hits: 0,
        misses: 0,
        url: "ro-hiragana",
        name: "ro",
    },
    {
        hits: 0,
        misses: 0,
        url: "te-hiragana",
        name: "te",
    },
    {
        hits: 0,
        misses: 0,
        url: "yu-hiragana",
        name: "yu",
    },
    {
        hits: 0,
        misses: 0,
        url: "hi-hiragana",
        name: "hi",
    },
    {
        hits: 0,
        misses: 0,
        url: "ma-hiragana",
        name: "ma",
    },
    {
        hits: 0,
        misses: 0,
        url: "ni-hiragana",
        name: "ni",
    },
    {
        hits: 0,
        misses: 0,
        url: "ru-hiragana",
        name: "ru",
    },
    {
        hits: 0,
        misses: 0,
        url: "to-hiragana",
        name: "to",
    },
    {
        hits: 0,
        misses: 0,
        url: "ho-hiragana",
        name: "ho",
    },
    {
        hits: 0,
        misses: 0,
        url: "me-hiragana",
        name: "me",
    },
    {
        hits: 0,
        misses: 0,
        url: "no-hiragana",
        name: "no",
    },
    {
        hits: 0,
        misses: 0,
        url: "sa-hiragana",
        name: "sa",
    },
    {
        hits: 0,
        misses: 0,
        url: "tsu-hiragana",
        name: "tsu",
    },
];
